/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetAppRouteImport } from './routes/get-app'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocIdRouteImport } from './routes/doc.$id'
import { Route as FolderIdRouteImport } from './routes/folder.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAppRoute = GetAppRouteImport.update({
  id: '/get-app',
  path: '/get-app',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderIdRoute = FolderIdRouteImport.update({
  id: '/folder/$id',
  path: '/folder/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-app': typeof GetAppRoute
  '/library': typeof LibraryRoute
  '/qr': typeof QrRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/doc/$id': typeof DocIdRoute
  '/folder/$id': typeof FolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-app': typeof GetAppRoute
  '/library': typeof LibraryRoute
  '/qr': typeof QrRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/doc/$id': typeof DocIdRoute
  '/folder/$id': typeof FolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-app': typeof GetAppRoute
  '/library': typeof LibraryRoute
  '/qr': typeof QrRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/doc/$id': typeof DocIdRoute
  '/folder/$id': typeof FolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-app'
    | '/library'
    | '/qr'
    | '/scan'
    | '/settings'
    | '/doc/$id'
    | '/folder/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-app'
    | '/library'
    | '/qr'
    | '/scan'
    | '/settings'
    | '/doc/$id'
    | '/folder/$id'
  id:
    | '__root__'
    | '/'
    | '/get-app'
    | '/library'
    | '/qr'
    | '/scan'
    | '/settings'
    | '/doc/$id'
    | '/folder/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetAppRoute: typeof GetAppRoute
  LibraryRoute: typeof LibraryRoute
  QrRoute: typeof QrRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  DocIdRoute: typeof DocIdRoute
  FolderIdRoute: typeof FolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-app': {
      id: '/get-app'
      path: '/get-app'
      fullPath: '/get-app'
      preLoaderRoute: typeof GetAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$id': {
      id: '/folder/$id'
      path: '/folder/$id'
      fullPath: '/folder/$id'
      preLoaderRoute: typeof FolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetAppRoute: GetAppRoute,
  LibraryRoute: LibraryRoute,
  QrRoute: QrRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  DocIdRoute: DocIdRoute,
  FolderIdRoute: FolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
